### ISSUE TITLE
Versions are wrong 

### ISSUE THREAD

**Issue by kurtbuilds** [frozenlib/structmeta#4]
The readme says structmeta is on `0.2`, which doesn't exist on master.

Workaround for now is

```toml
structmeta = { version = "0.1.6", git = "https://github.com/frozenlib/structmeta" }
```

which pulls in the syn 2.x dependency, but it'd be nice for versions to be fixed and use structmeta published on crates instead of github.

**Comment by frozenlib** [comment]
I just published version 0.2.0 on crates.io.
You can now use it as per the readme.
