### ISSUE TITLE
NameValue or Flag style?

### ISSUE THREAD

**Issue by sfackler** [frozenlib/structmeta#5]
Does `#[derive(StructMeta)]` support a NameValue or Flag style? This would support things like `#[serde(default)]` and `#[serde(default = "foo")]`. The docs don't seem to mention it as an option.

**Comment by frozenlib** [comment]
Currently, `NameValue or Flag style` is not implemented.

I would like to implement it in the future.

**Comment by frozenlib** [comment]
I have now implemented it. (5c8a9211782b166bd1b777afe949ca311840d20e.)

**Comment by sfackler** [comment]
Awesome, thanks!

**Comment by sfackler** [comment]
Any idea when you'll cut a new release? Looking forward to picking it up in https://github.com/sfackler/staged-builder :)

**Comment by frozenlib** [comment]
Hi,

Just published the updated package on crates.io with this fix.
